#pragma config(Sensor, in2,    armPotentL,     sensorPotentiometer)
#pragma config(Sensor, in3,    armPotent,      sensorPotentiometer)
#pragma config(Sensor, in4,    oranges,        sensorPotentiometer)
#pragma config(Sensor, in6,    turnGyro,       sensorGyro)
#pragma config(Sensor, in7,    flipPotent,     sensorPotentiometer)
#pragma config(Sensor, in8,    stackPotent,    sensorPotentiometer)
#pragma config(Sensor, dgtl1,  right,          sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  left,           sensorQuadEncoder)
#pragma config(Sensor, dgtl8,  coneTouch,      sensorTouch)
#pragma config(Sensor, dgtl9,  auton3,         sensorTouch)
#pragma config(Sensor, dgtl10, auton2,         sensorTouch)
#pragma config(Sensor, dgtl11, auton1,         sensorTouch)
#pragma config(Sensor, dgtl12, auton0,         sensorTouch)
#pragma config(Motor,  port1,           coneFlip,      tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           TBRmotor2,     tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           MRmotor3,      tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port5,           armMotorR,     tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           armMotorL,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           mGoalIntake,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           MLmotor8,      tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           TBLmotor9,     tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port10,          coneStack,     tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*        Description: Competition template for VEX EDR                      */
/*                                                                           */
/*---------------------------------------------------------------------------*/

// This code is for the VEX cortex platform
#pragma platform(VEX2)

// Select Download method as "competition"
#pragma competitionControl(Competition)

#include "Vex_Competition_Includes.c"
#include "worldsAutonFunctions2.c"
#include "worldsDriving2.c"
//#include "skills_autonomous_62_fix.c"
#include "worldsMobileGoal2.c"
#include "basicArmLift2.c"
#include "hoopTask2.c"
#include "switchCases.c"
#include "basicStackerLift2.c"
#include "twistAndLift2.c"
#include "worldsAutonomous2_5.c"
#include "balanceArm.c"

/*---------------------------------------------------------------------------*/
/*                          Pre-Autonomous Functions                         */
/*                                                                           */
/*  You may want to perform some actions before the competition starts.      */
/*  Do them in the following function.  You must return from this function   */
/*  or the autonomous and usercontrol tasks will not be started.  This       */
/*  function is only called once after the cortex has been powered on and    */
/*  not every time that the robot is disabled.                               */
/*---------------------------------------------------------------------------*/

void pre_auton()
{
	// Set bStopTasksBetweenModes to false if you want to keep user created tasks
	// running between Autonomous and Driver controlled modes. You will need to
	// manage all user created tasks if set to false.
	bStopTasksBetweenModes = true;

	// Set bDisplayCompetitionStatusOnLcd to false if you don't want the LCD
	// used by the competition include file, for example, you might want
	// to display your team name on the LCD in this function.
	// bDisplayCompetitionStatusOnLcd = false;

	// All activities that occur before the competition starts
	// Example: clearing encoders, setting servo positions, ...
	SensorType[in6] = sensorNone;
  wait1Msec(500);
  //Reconfigure Analog Port 8 as a Gyro sensor and allow time for ROBOTC to calibrate it
  SensorType[in6] = sensorGyro;
  wait1Msec(500);

  if (SensorValue[auton0] == 1)
  {
  	autonChoosen = 3;
  }

  else if (SensorValue[auton1] == 1)
  {
  	autonChoosen = 1;
  }

  else if (SensorValue[auton2] == 1)
  {
  	autonChoosen = 2;
  }

  else if (SensorValue[auton3] == 1)
  {
  	autonChoosen = 0;
  }

  else
  {
  	autonChoosen = 0;
  }
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              Autonomous Task                              */
/*                                                                           */
/*  This task is used to control your robot during the autonomous phase of   */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task autonomous()
{
	startTask(hoopTask);
	startTask(basicArmLift);
	startTask(basicStackerLift);
	startTask(theER);
	//startTask(mobileGoalTask);
	//startTask(drivingTask);
	//startTask(balanceArm);
	startTask(twistAndLift);
	SensorValue[turnGyro] = 0;
	wait1Msec(500);
	startTask(matchAuton);
}

/*---------------------------------------------------------------------------*/
/*                                                                           */
/*                              User Control Task                            */
/*                                                                           */
/*  This task is used to control your robot during the user control phase of */
/*  a VEX Competition.                                                       */
/*                                                                           */
/*  You must modify the code to add your own robot specific commands here.   */
/*---------------------------------------------------------------------------*/

task usercontrol()
{
	noSensor = 0;
	SensorValue[turnGyro] = 0;
	wait1Msec(500);

	startTask(mobileGoalTask);
	startTask(drivingTask);
	startTask(theER);
	//startTask(coneArm);
	startTask(hoopTask);
	//startTask(first);
	//startTask(countCones);
	//startTask(flipperLift);
	startTask(basicArmLift);
	startTask(basicStackerLift);
	startTask(twistAndLift);
	startTask(balanceArm);
	startTask(armControl);
}
